version: '3'

services:
  redmine:
    image: redmine:latest
    container_name: redmine
    environment:
      - TZ=Europe/Moscow
      - REDMINE_DB_POSTGRES=redmine
      - REDMINE_DB_POSTGRES=194.67.205.188
      - REDMINE_DB_USER=postgres
      - REDMINE_DB_PASSWORD=us_car_ga
#      - POSTGRES_PASSWORD='us_car_ga'
#      - POSTGRES_USER=postgres
    labels:
      - "traefik.backend=redmine"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:redmine.uscar.ga"
      - "traefik.enable=true"
    expose:
      - 3000
    volumes:
      - /srv/docker/redmine/data:/home/redmine/data
    networks:
      - traefik

networks:
  traefik:
    external: true

